# fly.toml app configuration file generated for vaers-mcp-server on 2025-06-03T12:29:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vaers-mcp-server'
primary_region = 'ord'

[build]
  dockerfile = 'apps/mcp-server/Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3001'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512